#!/usr/bin/env bash

args=()
init=false
workdir=$(pwd)
for i in "$@"; do
  case $i in
    -chdir=*)
      workdir="${i#*=}"
      args+=("$i")
      ;;
    -i)
      init=auto
      ;;
    -if)
      init=force
      ;;
    *)
      args+=("$i")
      ;;
  esac
done


# find is more reliable for file existence checks compared to `ls`
if [[ $init == "auto" ]] && [[ -n $(find "$workdir" -maxdepth 1 -name "*.tf" -print -quit 2>/dev/null) ]]; then
  if [[ ! -f "${workdir}/.terraform.lock.hcl" ]] || [[ ! -d "${workdir}/.terraform" ]]; then
    echo "${workdir}/.terraform.lock.hcl is not found and there are terraform files"
    tf init
  else
    echo "Both .terraform.lock.hcl and .terraform exists. Skipping. Run with -if option to force init"
  fi
elif [[ $init == "force" ]]; then
  tf init
fi

# use TF_BIN if it's set
# otherwise check the path of tofu
tf_bin=${TF_BIN:-$(which tofu)}

# shellcheck disable=SC2145
[[ $TF_COMMAND_SHOW != false ]] && >&2 echo "$tf_bin ${args[@]}"

$tf_bin "${args[@]}"

