#!/usr/bin/env bash

function _k8_resource_completion() {
  local _cmd=${COMP_WORDS[0]}
  resource=$(grep $_cmd < $KUBE_ARTIFACTS_DIR/dyn_render_func_mapping | head -n 1 | awk '{print $1}')
  if [[ -n $resource ]]; then
    COMPREPLY=($(compgen -W "$(_k8_cached_get $resource)"))
  fi
}

while read -r line; do
  complete -F _k8_resource_completion $(echo "$line")
done < $KUBE_ARTIFACTS_DIR/dyn_render_func_mapping

function _k_ns_completion() {
  local namespaces=$(KUBE_COMMAND_SHOW=false kg ns --no-headers -o custom-columns=:metadata.name)
  COMPREPLY=($(compgen -W "$namespaces"))
  return 0
}

function _k_pod_completion() {
  local services=$(KUBE_COMMAND_SHOW=false k-pod --no-headers -o custom-columns=:metadata.name)
  COMPREPLY=($(compgen -W "$services"))
  return 0
}

function _k_yaml_completion() {
  local files=$(ls -p | grep "\.yaml")
  COMPREPLY=($(compgen -W "$files"))
  return 0
}

function _k_deploy_completion() {
  local deploys=$(KUBE_COMMAND_SHOW=false kng deploy --no-headers -o custom-columns=:metadata.name)
  COMPREPLY=($(compgen -W "$deploys"))
  return 0
}

function _k_service_completion() {
  local servs=$(KUBE_COMMAND_SHOW=false kng service --no-headers -o custom-columns=:metadata.name)
  COMPREPLY=($(compgen -W "$servs"))
  return 0
}

function _k_secret_completion() {
  local secrets=$(KUBE_COMMAND_SHOW=false kng secret --no-headers -o custom-columns=:metadata.name)
  COMPREPLY=($(compgen -W "$secrets"))
  return 0
}

function _k_sec64_completion() {
  local reply=""
  if [ ${COMP_CWORD} == "1" ]; then
    reply=$(KUBE_COMMAND_SHOW=false kng secret --no-headers -o custom-columns=:metadata.name)
    COMPREPLY=($(compgen -W "$reply"))
  elif [ ${COMP_CWORD} == "2" ]; then
    local secret=${COMP_WORDS[1]}
    all_data=$(KUBE_COMMAND_SHOW=false k-sec $secret -o json | jq -r ".data")
    COMPREPLY=($(echo "$all_data" | jq "keys[]" -r))
  fi
  return 0
}


function _k_ctx_completion() {
  local ctxs=""
  if [[ -f "$HOME/.kube/config" ]]; then
    ctxs=$(yq -r '.contexts[].name' "$HOME/.kube/config")
  else
    ctxs=$(kubectl config view -o json | jq -r '.contexts[].name')
  fi
  COMPREPLY=($(compgen -W "$ctxs"))
  return 0
}

function _k_fwd_completion() {
  local reply=""
  if [ ${COMP_CWORD} == "1" ]; then
    reply=$(KUBE_COMMAND_SHOW=false kng pod --no-headers -o custom-columns=:metadata.name)
  elif [ ${COMP_CWORD} == "2" ]; then
    reply=$(cat $KUBE_PORT_ALIAS_FILE | awk '{print $1}')
  fi
  COMPREPLY=($(compgen -W "$reply"))
  return 0
}

function _ks_completion() {
  reply=$(cat $KUBE_NAMESPACE_CLUSTER_ALIAS_FILE | awk '{print $1;}')
  COMPREPLY=($(compgen -W "$reply"))
  return 0
}

function _k_resource_completion() {
  local reply=""
  if [ ${COMP_CWORD} == "1" ]; then
    reply=$(KUBE_COMMAND_SHOW=false k api-resources --verbs=list | tail -n +2 | awk '{print $1}')
  elif [ ${COMP_CWORD} == "2" ]; then
    reply=$(KUBE_COMMAND_SHOW=false kn get ${COMP_WORDS[$COMP_CWORD-1]} | tail -n +3 | awk '{print $1}')
  fi
  COMPREPLY=($(compgen -W "$reply"))
  return 0
}

function _k_node_completion() {
  local nodes=$(KUBE_COMMAND_SHOW=false kg node --no-headers -o custom-columns=:metadata.name)
  COMPREPLY=($(compgen -W "$nodes"))
  return 0
}

function _k_cron_completion() {
  local cron=$(KUBE_COMMAND_SHOW=false kng cronjob --no-headers -o custom-columns=:metadata.name)
  COMPREPLY=($(compgen -W "$cron"))
  return 0
}

function _k_ss_completion() {
  local ss=$(KUBE_COMMAND_SHOW=false kng statefulset --no-headers -o custom-columns=:metadata.name)
  COMPREPLY=($(compgen -W "$ss"))
  return 0
}

complete -F _k_ctx_completion k-ctx
complete -F _k_fwd_completion k-fwd
complete -F _ks_completion ks
complete -F _k_resource_completion knd kng knx kd kg kx kne ke
complete -F _k_node_completion k-npod
