#!/usr/bin/env bash

# use the first container if -c is not set
file=""
template_type=""
substitute="false"
_env_vars=""
image=""
labels=""
args=()
dry="false"
node=""
pod_node=""
zone=""
rm="--rm"
volumes="[]"
mounts="[]"
environments="[]"

for i in "$@"; do
  case $i in
    --no-rm)
      rm=""
      shift;;
    --i=*|--image=*)
      image="${i#*=}"
      shift;;
    -l=*|--label=*)
      label="${i#*=}"
      [[ -z "$labels" ]] && labels="{}"
      key=${label%=*}
      value=${label#*=}
      labels=$(echo "$labels" | jq --arg key "$key" --arg value "$value" '.[$key] = $value')
      shift;;
    --env=*|-e=*)
      add_env="${i#*=}"
      if [[ $add_env == *"="* ]]; then
        name="${add_env%=*}"
        value="${add_env#*=}"
      else
        name="$add_env"
        value="${!name}"
      fi
      environments=$(echo "$environments" | jq --argjson env '[{"name": "'$name'","value":"'$value'"}]' '. += $env')
      shift;;
    --node=*)
      node="${i#*=}"
      shift;;
    --zone=*)
      zone="${i#*=}"
      shift;;
    --pod-node=*)
      pod_node="${i#*=}"
      shift;;
    -)
      file="-"
      shift;;
    -f=*)
      file="${i#*=}"
      shift;;
    --dry)
      dry=true
      shift;;
    -D*)
      substitute=true
      # get all string after -D
      _arg="${i#-D*}"
      # var name is the string before =, with _replace_ prefix
      _var="_replace_${_arg%%=*}"
      # value is the string after =
      _val="${_arg#*=}"
      # export the variable, so envsubst can use it
      export $_var="$_val"
      _env_vars="\$${_var} $_env_vars"
      shift;;
    --subst)
      substitute=true
      shift;;
    --mount-secret=*|-ms=*)
      sec_mount="${i#*=}"
      mount=$(echo "$sec_mount" | yq -o json '{"mountPath": .path, "name": .name}' | jq -rc)
      volume=$(echo "$sec_mount" | yq -o json '{"name": .name, "secret": {"secretName": .name}}' | jq -rc)
      volumes=$(echo "$volumes" | jq --argjson entry "[$volume]" '. += $entry')
      mounts=$(echo "$mounts" | jq --argjson entry "[$mount]" '. += $entry')
      shift;;
    --mount-cm=*|-mc=*)
      sec_mount="${i#*=}"
      mount=$(echo "$sec_mount" | yq -o json '{"mountPath": .path, "name": .name}' | jq -rc)
      volume=$(echo "$sec_mount" | yq -o json '{"name": .name, "configMap": {"configMapName": .name}}' | jq -rc)
      volumes=$(echo "$volumes" | jq --argjson entry "[$volume]" '. += $entry')
      mounts=$(echo "$mounts" | jq --argjson entry "[$mount]" '. += $entry')
      shift;;
    --t=*|--template=*)
      file="$KUBE_ARTIFACTS_DIR/template/${i#*=}"
      if [[ -f "$file.yaml" ]]; then
        template_type="yaml"
        file="$file.yaml"
      elif [[ -f "$file.json" ]]; then
        template_type="json"
        file="$file.json"
      fi
      shift;;
    *)
      args+=("$i")
      shift
      ;;
  esac
done

overrides=""

if [[ $file == "-" ]] || [[ -f $file ]]; then
  overrides=$(cat "$file")
  if [[ $substitute == "true" ]]; then
    overrides=$(envsubst "$_env_vars" <<< "$overrides")
  fi

  # transform yaml to json
  if [[ $template_type == "yaml" ]]; then
    overrides=$(echo "$overrides" | yq -o=json)
  fi

  overrides=$(echo "$overrides" | jq -c '.')

  # try to get the image from the template from the overrides if it doesn't exist
  if [[ -z $image ]]; then
    image=$(echo "$overrides" | jq -r '.spec.containers[0].image')
  fi
fi

if [[ -n $pod_node ]]; then
  node=$(k-pod --no-headers -o custom-columns=:spec.nodeName $pod_node)
fi

if [[ -n $node ]]; then
  [[ -z $overrides ]] && overrides="{}"
  overrides=$(echo "$overrides" | jq --arg node "$node" '.spec.nodeName = $node')
elif [[ -n $zone ]]; then
  [[ -z $overrides ]] && overrides="{}"
  overrides=$(echo "$overrides" | jq --arg zone "$zone" '.spec.nodeSelector["topology.kubernetes.io/zone"] = $zone')
fi

if [[ -z $image ]]; then
  echo "Image is not set. Either ensure that you have an image in overrides or supply it via --i or --image"
  exit 1
fi

if [[ -n "$labels" ]]; then
  [[ -z $overrides ]] && overrides="{}"
  overrides=$(echo "$overrides" | jq --argjson labels "$labels" '.metadata.labels = $labels')
fi

if [[ "$volumes" != '[]' ]]; then
  overrides=$(echo "$overrides" | jq --argjson volumes "$volumes" '.spec.volumes = $volumes')
fi

if [[ "$mounts" != '[]' ]]; then
  overrides=$(echo "$overrides" | jq --argjson mounts "$mounts" '.spec.containers[0].volumeMounts = $mounts')
fi

if [[ "$environments" != '[]' ]]; then
  overrides=$(echo "$overrides" | jq --argjson env "$environments" '.spec.containers[0].env = $env')
fi

# shellcheck disable=SC2145
[[ $KUBE_COMMAND_SHOW != false ]] && >&2 echo "kubectl $(_k8_flag ctx) $(_k8_flag ns) run --overrides='$overrides' -i --tty $rm $name --image=$image ${args[@]}"

# shellcheck disable=SC2046
[[ $dry == "false" ]] && kubectl $(_k8_flag ctx) $(_k8_flag ns) run --overrides="$overrides" -i --tty $rm --image="$image" "${args[@]}"
