#!/usr/bin/env bash

function _cdtl_completion() {
  if [[ "$COMP_CWORD" == "1" ]]; then
    COMPREPLY=($(compgen -W "cd .."))
  else
    case "${COMP_WORDS[1]}" in
      cd)
        _cdtl_completion_cd
        ;;
    esac
  fi
}

function _cdtl_completion_cd() {
  COMPREPLY=($(compgen -W "$(_cdtl_template | jq -r '.groups' | tr ' ' '\n' | grep -v head | grep -v tail | xargs -I {} -n 1 echo "-{}")"))
}

complete -F _cdtl_completion cdtl