#!/usr/bin/env bash

source "$CLYDESH_HOME/utils.sh"

replacements=$(_cdtl_replacement "$@")
template=$(_cdtl_template "$PWD")

groups=$(echo "$template" | jq -r ".groups")
matched=$(echo "$template" | jq ".matched")

if [[ $CDTL_DEBUG == "true" ]]; then
  >&2 echo "changing dir template: $template"
  >&2 echo "with replacement: $replacements"
fi

function join_by { local IFS="$1"; shift; echo "$*"; }

path_tokens=()
for g in $groups; do
  rep=$(echo "$replacements" | jq -r ".$g")
  if [[ -z $rep ]] || [[ $rep == "null" ]]; then
    old_value=$(echo "$matched" | jq -r ".$g")
    path_tokens+=("$old_value")
  else
    path_tokens+=("$(t-green "$rep")")
  fi
done

join_by / "${path_tokens[@]}"
